version: '3.8'

services:
  mysqldb:
    image: mysql:8.3
    container_name: cms-database
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cms24
      MYSQL_PASSWORD: cms24
      MYSQL_DATABASE: cms-beweb
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin
    container_name: cms-phpmyadmin
    environment:
      PMA_HOST: mysqldb
    links:
      - mysqldb:mysqldb
    ports:
      - 8090:80

  sonarqube:
    image: sonarqube:latest
    container_name: cms-sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
